---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dr-pipeline
  namespace: dr-pipelines
  labels:
    app.kubernetes.io/part-of: netapp-dr-starter-kit
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dr-pipeline-cluster-admin
  labels:
    app.kubernetes.io/part-of: netapp-dr-starter-kit
subjects:
  - kind: ServiceAccount
    name: dr-pipeline
    namespace: dr-pipelines
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
