# Generated by patternizer
# This Makefile includes the common pattern targets from Makefile-common
# You can add custom targets above or below the include line

include Makefile-common

# =============================================================================
# NetApp DR Starter Kit - Infrastructure Targets
# =============================================================================
#
# These targets manage the DR infrastructure:
#   - Terraform state backend (S3 bucket + DynamoDB from values-trident.yaml)
#   - Cluster discovery (auto-detect VPC, CIDR, region from kubeconfigs)
#   - VPC peering between prod and DR clusters
#   - FSx for NetApp ONTAP filesystems in each region
#
# Required:
#   PROD_KUBECONFIG - path to production cluster kubeconfig
#   DR_KUBECONFIG   - path to DR cluster kubeconfig
#
# The terraform state bucket name is read from values-trident.yaml
# (.terraform.state.bucket) automatically by the playbook.
# =============================================================================

# Expand ~ in kubeconfig paths
PROD_KUBECONFIG ?=
DR_KUBECONFIG ?=
_PROD_KUBECONFIG := $(if $(PROD_KUBECONFIG),$(shell echo $(PROD_KUBECONFIG)),)
_DR_KUBECONFIG := $(if $(DR_KUBECONFIG),$(shell echo $(DR_KUBECONFIG)),)
EXTRA_PLAYBOOK_OPTS ?=

# Optional overrides (empty = auto-detect from cluster)
PROD_CLUSTER ?=
DR_CLUSTER ?=
PROD_REGION ?=
DR_REGION ?=
PROD_VPC_CIDR ?=
DR_VPC_CIDR ?=

# Build the -e extra-vars string from overrides
_DR_EXTRA_VARS := -e prod_kubeconfig=$(_PROD_KUBECONFIG) -e dr_kubeconfig=$(_DR_KUBECONFIG)
ifneq ($(PROD_CLUSTER),)
  _DR_EXTRA_VARS += -e prod_cluster_name_override=$(PROD_CLUSTER)
endif
ifneq ($(DR_CLUSTER),)
  _DR_EXTRA_VARS += -e dr_cluster_name_override=$(DR_CLUSTER)
endif
ifneq ($(PROD_REGION),)
  _DR_EXTRA_VARS += -e prod_region_override=$(PROD_REGION)
endif
ifneq ($(DR_REGION),)
  _DR_EXTRA_VARS += -e dr_region_override=$(DR_REGION)
endif
ifneq ($(PROD_VPC_CIDR),)
  _DR_EXTRA_VARS += -e prod_vpc_cidr_override=$(PROD_VPC_CIDR)
endif
ifneq ($(DR_VPC_CIDR),)
  _DR_EXTRA_VARS += -e dr_vpc_cidr_override=$(DR_VPC_CIDR)
endif

# Validation
define _validate_kubeconfigs
	@if [ -z "$(_PROD_KUBECONFIG)" ]; then \
		echo "Error: PROD_KUBECONFIG is required."; \
		echo "Usage: make $(1) PROD_KUBECONFIG=/path/to/prod DR_KUBECONFIG=/path/to/dr"; \
		exit 1; \
	fi
	@if [ -z "$(_DR_KUBECONFIG)" ]; then \
		echo "Error: DR_KUBECONFIG is required."; \
		echo "Usage: make $(1) PROD_KUBECONFIG=/path/to/prod DR_KUBECONFIG=/path/to/dr"; \
		exit 1; \
	fi
	@if [ ! -f "$(_PROD_KUBECONFIG)" ]; then \
		echo "Error: PROD_KUBECONFIG file not found: $(_PROD_KUBECONFIG)"; \
		exit 1; \
	fi
	@if [ ! -f "$(_DR_KUBECONFIG)" ]; then \
		echo "Error: DR_KUBECONFIG file not found: $(_DR_KUBECONFIG)"; \
		exit 1; \
	fi
endef

##@ NetApp DR Infrastructure

.PHONY: build-dr
build-dr: ## Build complete DR infrastructure (state backend, VPC peering, FSx filesystems)
	$(call _validate_kubeconfigs,build-dr)
	@echo "=========================================="
	@echo "Building DR Infrastructure"
	@echo "  Prod kubeconfig: $(_PROD_KUBECONFIG)"
	@echo "  DR kubeconfig:   $(_DR_KUBECONFIG)"
	@echo "  State bucket:    from values-trident.yaml"
	@echo "=========================================="
	ansible-playbook $(EXTRA_PLAYBOOK_OPTS) ansible/dr-setup.yaml \
		-e @ansible/dr-vars.yml \
		$(_DR_EXTRA_VARS)

.PHONY: destroy-dr
destroy-dr: ## Destroy DR infrastructure (FSx filesystems and VPC peering; preserves state bucket)
	$(call _validate_kubeconfigs,destroy-dr)
	@echo "=========================================="
	@echo "Destroying DR Infrastructure"
	@echo "  Prod kubeconfig: $(_PROD_KUBECONFIG)"
	@echo "  DR kubeconfig:   $(_DR_KUBECONFIG)"
	@echo "  Note: State bucket is preserved"
	@echo "=========================================="
	ansible-playbook $(EXTRA_PLAYBOOK_OPTS) ansible/dr-setup.yaml \
		-e @ansible/dr-vars.yml \
		$(_DR_EXTRA_VARS) \
		-e destroy_resources=true

# Trident Protect AppVault S3 bucket from values-global.yaml
_APPVAULT_BUCKET := $(shell yq '.tridentProtect.appVault.s3.bucketName // ""' values-global.yaml 2>/dev/null)
_APPVAULT_REGION := $(shell yq '.tridentProtect.appVault.s3.region // ""' values-global.yaml 2>/dev/null)

.PHONY: create-appvault-bucket
create-appvault-bucket: ## Create the S3 bucket for Trident Protect AppVault
	@if [ -z "$(_APPVAULT_BUCKET)" ]; then \
		echo "Error: Could not read .tridentProtect.appVault.s3.bucketName from values-global.yaml"; \
		exit 1; \
	fi
	@if [ -z "$(_APPVAULT_REGION)" ]; then \
		echo "Error: Could not read .tridentProtect.appVault.s3.region from values-global.yaml"; \
		exit 1; \
	fi
	@echo "=========================================="
	@echo "Trident Protect AppVault S3 Bucket"
	@echo "=========================================="
	@echo "  Bucket: $(_APPVAULT_BUCKET)"
	@echo "  Region: $(_APPVAULT_REGION)"
	@echo "=========================================="
	@if aws s3api head-bucket --bucket $(_APPVAULT_BUCKET) --region $(_APPVAULT_REGION) 2>/dev/null; then \
		echo "Bucket '$(_APPVAULT_BUCKET)' already exists - nothing to do."; \
	else \
		echo "Creating S3 bucket '$(_APPVAULT_BUCKET)' in $(_APPVAULT_REGION)..."; \
		if [ "$(_APPVAULT_REGION)" = "us-east-1" ]; then \
			aws s3api create-bucket \
				--bucket $(_APPVAULT_BUCKET) \
				--region $(_APPVAULT_REGION); \
		else \
			aws s3api create-bucket \
				--bucket $(_APPVAULT_BUCKET) \
				--region $(_APPVAULT_REGION) \
				--create-bucket-configuration LocationConstraint=$(_APPVAULT_REGION); \
		fi; \
		echo "Bucket '$(_APPVAULT_BUCKET)' created."; \
	fi

# State bucket name, DynamoDB table, and region from values-trident.yaml
_STATE_BUCKET := $(shell yq '.terraform.state.bucket // ""' values-trident.yaml 2>/dev/null)
_DYNAMODB_TABLE := $(shell yq '.terraform.state.dynamodb_table // "terraform-state-lock"' values-trident.yaml 2>/dev/null)
_STATE_REGION := $(shell yq '.terraform.state.region // "us-east-1"' values-trident.yaml 2>/dev/null)

.PHONY: destroy-terraform-state
destroy-terraform-state: ## Destroy the Terraform state backend (S3 bucket + DynamoDB table) - DESTRUCTIVE
	@if [ -z "$(_STATE_BUCKET)" ]; then \
		echo "Error: Could not read .terraform.state.bucket from values-trident.yaml"; \
		exit 1; \
	fi
	@echo "=========================================="
	@echo "WARNING: Destroying Terraform State Backend"
	@echo "=========================================="
	@echo "  S3 Bucket:      $(_STATE_BUCKET)"
	@echo "  DynamoDB Table: $(_DYNAMODB_TABLE)"
	@echo "  Region:         $(_STATE_REGION)"
	@echo ""
	@echo "  This will permanently delete all Terraform state!"
	@echo "  Make sure you have destroyed all DR resources first"
	@echo "  (make destroy-dr) or they will become orphaned."
	@echo "=========================================="
	@echo ""
	@read -p "Type 'yes' to confirm: " confirm && [ "$$confirm" = "yes" ] || (echo "Aborted."; exit 1)
	@echo ""
	@echo "--- Emptying S3 bucket (all object versions) ---"
	@aws s3api list-object-versions \
		--bucket $(_STATE_BUCKET) \
		--region $(_STATE_REGION) \
		--query '{Objects: Versions[].{Key:Key,VersionId:VersionId}}' \
		--output json 2>/dev/null | \
	python3 -c "\
	import sys, json, subprocess; \
	data = json.load(sys.stdin); \
	objects = data.get('Objects') or []; \
	[subprocess.run(['aws', 's3api', 'delete-objects', '--bucket', '$(_STATE_BUCKET)', '--region', '$(_STATE_REGION)', '--delete', json.dumps({'Objects': objects[i:i+1000], 'Quiet': True})], check=True) for i in range(0, len(objects), 1000)] if objects else None; \
	print(f'Deleted {len(objects)} object versions') if objects else print('No object versions to delete')" || true
	@echo "--- Removing delete markers ---"
	@aws s3api list-object-versions \
		--bucket $(_STATE_BUCKET) \
		--region $(_STATE_REGION) \
		--query '{Objects: DeleteMarkers[].{Key:Key,VersionId:VersionId}}' \
		--output json 2>/dev/null | \
	python3 -c "\
	import sys, json, subprocess; \
	data = json.load(sys.stdin); \
	objects = data.get('Objects') or []; \
	[subprocess.run(['aws', 's3api', 'delete-objects', '--bucket', '$(_STATE_BUCKET)', '--region', '$(_STATE_REGION)', '--delete', json.dumps({'Objects': objects[i:i+1000], 'Quiet': True})], check=True) for i in range(0, len(objects), 1000)] if objects else None; \
	print(f'Removed {len(objects)} delete markers') if objects else print('No delete markers to remove')" || true
	@echo "--- Deleting S3 bucket ---"
	@aws s3api delete-bucket --bucket $(_STATE_BUCKET) --region $(_STATE_REGION) \
		&& echo "S3 bucket '$(_STATE_BUCKET)' deleted" \
		|| echo "S3 bucket '$(_STATE_BUCKET)' not found (already deleted?)"
	@echo "--- Deleting DynamoDB table ---"
	@aws dynamodb delete-table --table-name $(_DYNAMODB_TABLE) --region $(_STATE_REGION) > /dev/null 2>&1 \
		&& echo "DynamoDB table '$(_DYNAMODB_TABLE)' deleted" \
		|| echo "DynamoDB table '$(_DYNAMODB_TABLE)' not found (already deleted?)"
	@echo "--- Cleaning local working directory ---"
	@rm -rf /tmp/netapp-dr-terraform/terraform-state
	@echo ""
	@echo "=========================================="
	@echo "  Terraform State Backend Destroyed"
	@echo "=========================================="

# =============================================================================
# Pipeline Targets
# =============================================================================

PIPELINE_NS ?= dr-pipelines
PIPELINE_IMAGE ?= quay.io/day0hero/dr-pipeline-tools:latest
GIT_URL ?= $(shell git remote get-url origin 2>/dev/null)
GIT_BRANCH ?= $(shell git rev-parse --abbrev-ref HEAD 2>/dev/null || echo main)

##@ Pipeline

.PHONY: verify-prerequisites
verify-prerequisites: ## Run the prerequisites verification playbook locally
	$(call _validate_kubeconfigs,verify-prerequisites)
	ansible-playbook ansible/verify-prerequisites.yaml \
		-e prod_kubeconfig=$(_PROD_KUBECONFIG) \
		-e dr_kubeconfig=$(_DR_KUBECONFIG)

.PHONY: pipeline-setup
pipeline-setup: ## Create pipeline namespace, RBAC, PVC, and apply task/pipeline definitions
	@echo "=========================================="
	@echo "Setting up DR Pipeline"
	@echo "  Namespace: $(PIPELINE_NS)"
	@echo "=========================================="
	oc apply -f pipelines/base/namespace.yaml
	oc apply -f pipelines/base/serviceaccount.yaml
	oc apply -f pipelines/base/pvc.yaml
	oc apply -f pipelines/tasks/
	oc apply -f pipelines/pipeline.yaml
	@echo ""
	@echo "Pipeline resources created. Now create secrets:"
	@echo "  oc create secret generic aws-credentials -n $(PIPELINE_NS) \\"
	@echo "    --from-literal=AWS_ACCESS_KEY_ID=<key> \\"
	@echo "    --from-literal=AWS_SECRET_ACCESS_KEY=<secret>"
	@echo ""
	@echo "  oc create secret generic fsx-admin-password -n $(PIPELINE_NS) \\"
	@echo "    --from-literal=password=<fsx-password>"
	@echo ""
	@echo "  oc create secret generic git-credentials -n $(PIPELINE_NS) \\"
	@echo "    --from-literal=username=<github-user> \\"
	@echo "    --from-literal=password=<github-pat>"
	@echo ""
	@echo "  oc create secret generic prod-kubeconfig -n $(PIPELINE_NS) \\"
	@echo "    --from-file=kubeconfig=<path-to-prod-kubeconfig>"
	@echo ""
	@echo "  oc create secret generic dr-kubeconfig -n $(PIPELINE_NS) \\"
	@echo "    --from-file=kubeconfig=<path-to-dr-kubeconfig>"

.PHONY: pipeline-secrets
pipeline-secrets: ## Create pipeline secrets from local files (interactive)
	$(call _validate_kubeconfigs,pipeline-secrets)
	@echo "Creating pipeline secrets in $(PIPELINE_NS)..."
	@oc create secret generic aws-credentials -n $(PIPELINE_NS) \
		--from-literal=AWS_ACCESS_KEY_ID=$$(aws configure get aws_access_key_id) \
		--from-literal=AWS_SECRET_ACCESS_KEY=$$(aws configure get aws_secret_access_key) \
		--dry-run=client -o yaml | oc apply -f -
	@if [ -f "$$HOME/.fsx" ]; then \
		oc create secret generic fsx-admin-password -n $(PIPELINE_NS) \
			--from-literal=password=$$(cat $$HOME/.fsx) \
			--dry-run=client -o yaml | oc apply -f -; \
	else \
		echo "WARNING: ~/.fsx not found - create fsx-admin-password secret manually"; \
	fi
	@oc create secret generic prod-kubeconfig -n $(PIPELINE_NS) \
		--from-file=kubeconfig=$(_PROD_KUBECONFIG) \
		--dry-run=client -o yaml | oc apply -f -
	@oc create secret generic dr-kubeconfig -n $(PIPELINE_NS) \
		--from-file=kubeconfig=$(_DR_KUBECONFIG) \
		--dry-run=client -o yaml | oc apply -f -
	@echo "Secrets created. Git credentials must be created manually:"
	@echo "  oc create secret generic git-credentials -n $(PIPELINE_NS) \\"
	@echo "    --from-literal=username=<github-user> \\"
	@echo "    --from-literal=password=<github-pat>"

.PHONY: pipeline-run
pipeline-run: ## Trigger a pipeline run
	@echo "Starting DR infrastructure pipeline..."
	oc create -f - <<EOF
	apiVersion: tekton.dev/v1
	kind: PipelineRun
	metadata:
	  generateName: provision-dr-infra-
	  namespace: $(PIPELINE_NS)
	spec:
	  pipelineRef:
	    name: provision-dr-infrastructure
	  params:
	    - name: git-url
	      value: "$(GIT_URL)"
	    - name: git-revision
	      value: "$(GIT_BRANCH)"
	  taskRunTemplate:
	    serviceAccountName: dr-pipeline
	  timeouts:
	    pipeline: "2h"
	    tasks: "1h30m"
	  workspaces:
	    - name: shared-workspace
	      persistentVolumeClaim:
	        claimName: dr-pipeline-workspace
	    - name: prod-kubeconfig
	      secret:
	        secretName: prod-kubeconfig
	    - name: dr-kubeconfig
	      secret:
	        secretName: dr-kubeconfig
	EOF

.PHONY: pipeline-image-build
pipeline-image-build: ## Build the pipeline tools container image
	podman build -t $(PIPELINE_IMAGE) -f pipelines/Containerfile pipelines/

.PHONY: pipeline-image-push
pipeline-image-push: pipeline-image-build ## Build and push the pipeline tools container image
	podman push $(PIPELINE_IMAGE)
