# Generated by patternizer
# This Makefile includes the common pattern targets from Makefile-common
# You can add custom targets above or below the include line

include Makefile-common

# Hub install uses PROD_KUBECONFIG as KUBECONFIG. Staged Argo waits avoid rhvp.cluster_utils.install
# failing while crossplane-aws-infra waits for in-cluster discovery (see ansible/wait-argo-applications.yaml).
# Kubeconfig paths default from ~/values-secret-netapp-dr-starter-kit.yaml (see values-secret.yaml.template).
_HUB_ANSIBLE = KUBECONFIG="$(_PROD_KUBECONFIG)" $(ANSIBLE_RUN)

.PHONY: install pattern-install-hub wait-argo-pre-bootstrap wait-argo-post-bootstrap
install: pattern-install-hub wait-argo-pre-bootstrap wait-crossplane-bootstrap wait-argo-post-bootstrap ## Hub install (kubeconfigs from values-secret or PROD_/DR_KUBECONFIG)

pattern-install-hub: ## Install pattern on hub (PROD_KUBECONFIG); skips blanket Argo health gate
	$(call _validate_kubeconfigs,install)
	@echo "Installing pattern on hub cluster (KUBECONFIG=$(_PROD_KUBECONFIG))..."
	@$(_HUB_ANSIBLE) rhvp.cluster_utils.load_bootstrap_secrets
	@$(_HUB_ANSIBLE) rhvp.cluster_utils.operator_deploy
	@$(_HUB_ANSIBLE) rhvp.cluster_utils.load_secrets

wait-argo-pre-bootstrap: ## Wait for hub Argo apps except crossplane-aws-infra / dr-dns-reconciler
	$(call _validate_kubeconfigs,wait-argo-pre-bootstrap)
	@echo "Waiting for hub Argo CD applications (pre Crossplane bootstrap)..."
	@$(ANSIBLE_RUN) ansible/wait-argo-applications.yaml \
		-e prod_kubeconfig=$(_PROD_KUBECONFIG) \
		-e wait_phase=pre_bootstrap

wait-argo-post-bootstrap: ## Wait for crossplane-aws-infra (and dr-dns) Synced after discovery
	$(call _validate_kubeconfigs,wait-argo-post-bootstrap)
	@echo "Waiting for Crossplane bootstrap Argo CD applications to sync..."
	@$(ANSIBLE_RUN) ansible/wait-argo-applications.yaml \
		-e prod_kubeconfig=$(_PROD_KUBECONFIG) \
		-e wait_phase=post_bootstrap

# =============================================================================
# NetApp DR Starter Kit - Infrastructure Targets
# =============================================================================
#
# These targets manage the DR infrastructure via Crossplane (GitOps):
#   - Cluster discovery (auto-detect VPC, CIDR, region from kubeconfigs)
#   - Crossplane values written to Helm values files
#   - ArgoCD syncs Crossplane managed resources (FSx, S3, VPC Peering, Route53)
#
# Kubeconfigs (first match wins):
#   PROD_KUBECONFIG / DR_KUBECONFIG  make variables
#   KUBECONFIG                       hub install only (if PROD not set)
#   ~/values-secret-<pattern>.yaml   ocp-primary / ocp-dr kubeconfig paths
# =============================================================================

PATTERN_NAME ?= netapp-dr-starter-kit
VALUES_SECRET ?=
_RESOLVE_KUBECONFIGS := $(abspath scripts/resolve_kubeconfigs_from_values_secret.py)

# Expand ~ in kubeconfig paths; else read from values-secret (same file load-secrets uses).
PROD_KUBECONFIG ?=
DR_KUBECONFIG ?=
_PROD_FROM_SECRET := $(shell PATTERN_NAME="$(PATTERN_NAME)" VALUES_SECRET="$(VALUES_SECRET)" python3 "$(_RESOLVE_KUBECONFIGS)" prod 2>/dev/null)
_DR_FROM_SECRET := $(shell PATTERN_NAME="$(PATTERN_NAME)" VALUES_SECRET="$(VALUES_SECRET)" python3 "$(_RESOLVE_KUBECONFIGS)" dr 2>/dev/null)
_PROD_KUBECONFIG := $(if $(PROD_KUBECONFIG),$(shell echo $(PROD_KUBECONFIG)),$(if $(KUBECONFIG),$(shell echo $(KUBECONFIG)),$(_PROD_FROM_SECRET)))
_DR_KUBECONFIG := $(if $(DR_KUBECONFIG),$(shell echo $(DR_KUBECONFIG)),$(_DR_FROM_SECRET))
_VALUES_SECRET_FILE := $(if $(VALUES_SECRET),$(shell echo $(VALUES_SECRET)),$(HOME)/values-secret-$(PATTERN_NAME).yaml)
EXTRA_PLAYBOOK_OPTS ?=

# Optional overrides (empty = auto-detect from cluster)
PROD_CLUSTER ?=
DR_CLUSTER ?=
PROD_REGION ?=
DR_REGION ?=
PROD_VPC_CIDR ?=
DR_VPC_CIDR ?=

# Build the -e extra-vars string from overrides
_DR_EXTRA_VARS := -e prod_kubeconfig=$(_PROD_KUBECONFIG) -e dr_kubeconfig=$(_DR_KUBECONFIG)
ifneq ($(PROD_CLUSTER),)
  _DR_EXTRA_VARS += -e prod_cluster_name_override=$(PROD_CLUSTER)
endif
ifneq ($(DR_CLUSTER),)
  _DR_EXTRA_VARS += -e dr_cluster_name_override=$(DR_CLUSTER)
endif
ifneq ($(PROD_REGION),)
  _DR_EXTRA_VARS += -e prod_region_override=$(PROD_REGION)
endif
ifneq ($(DR_REGION),)
  _DR_EXTRA_VARS += -e dr_region_override=$(DR_REGION)
endif
ifneq ($(PROD_VPC_CIDR),)
  _DR_EXTRA_VARS += -e prod_vpc_cidr_override=$(PROD_VPC_CIDR)
endif
ifneq ($(DR_VPC_CIDR),)
  _DR_EXTRA_VARS += -e dr_vpc_cidr_override=$(DR_VPC_CIDR)
endif

# Validation
define _validate_kubeconfigs
	@if [ -z "$(_PROD_KUBECONFIG)" ]; then \
		echo "Error: hub (primary) kubeconfig not found."; \
		echo "  Configure ocp-primary-cluster-kubeconfig in $(_VALUES_SECRET_FILE)"; \
		echo "  or pass PROD_KUBECONFIG=/path/to/prod (or export KUBECONFIG)."; \
		exit 1; \
	fi
	@if [ -z "$(_DR_KUBECONFIG)" ]; then \
		echo "Error: DR kubeconfig not found."; \
		echo "  Configure ocp-dr-cluster-kubeconfig in $(_VALUES_SECRET_FILE)"; \
		echo "  or pass DR_KUBECONFIG=/path/to/dr."; \
		exit 1; \
	fi
	@if [ ! -f "$(_PROD_KUBECONFIG)" ]; then \
		echo "Error: PROD_KUBECONFIG file not found: $(_PROD_KUBECONFIG)"; \
		exit 1; \
	fi
	@if [ ! -f "$(_DR_KUBECONFIG)" ]; then \
		echo "Error: DR_KUBECONFIG file not found: $(_DR_KUBECONFIG)"; \
		exit 1; \
	fi
endef

##@ NetApp DR Infrastructure

##@ Crossplane Infrastructure

.PHONY: wait-crossplane-bootstrap
wait-crossplane-bootstrap: ## After install: wait for discovery ConfigMap and two OntapFileSystem CRs on the hub
	$(call _validate_kubeconfigs,wait-crossplane-bootstrap)
	@echo "Waiting for Crossplane network discovery and dual FSx CRs (hub cluster)..."
	@$(ANSIBLE_RUN) ansible/wait-crossplane-bootstrap.yaml \
		-e prod_kubeconfig=$(_PROD_KUBECONFIG) \
		-e dr_kubeconfig=$(_DR_KUBECONFIG)

.PHONY: crossplane-setup
crossplane-setup: ## Optional: discover clusters and write Crossplane values locally (break-glass; default is in-cluster discovery)
	$(call _validate_kubeconfigs,crossplane-setup)
	@echo "=========================================="
	@echo "Crossplane Infrastructure Setup"
	@echo "  Prod kubeconfig: $(_PROD_KUBECONFIG)"
	@echo "  DR kubeconfig:   $(_DR_KUBECONFIG)"
	@echo "  (Route53: configure AWS credentials for hosted-zone discovery — no zone ID in Git)"
	@echo "=========================================="
	ansible-playbook $(EXTRA_PLAYBOOK_OPTS) ansible/crossplane-setup.yaml \
		-e @ansible/crossplane-vars.yml \
		$(_DR_EXTRA_VARS)
	@echo ""
	@echo "=========================================="
	@echo "  Values files updated. Next steps:"
	@echo "    1. git diff  (review changes)"
	@echo "    2. git add -A && git commit"
	@echo "    3. git push  (triggers ArgoCD sync)"
	@echo "    4. kubectl get managed  (monitor)"
	@echo "=========================================="

##@ Crossplane DR Teardown

.PHONY: destroy-dr dr-destroy
# dr-destroy is an alias (same recipe as destroy-dr)
destroy-dr dr-destroy: ## Destroy DR infrastructure (pauses ArgoCD, cleans ONTAP, deletes Crossplane resources)
	$(call _validate_kubeconfigs,destroy-dr)
	@echo "=========================================="
	@echo "WARNING: Destroying DR Infrastructure"
	@echo "=========================================="
	@echo "  Prod kubeconfig: $(_PROD_KUBECONFIG)"
	@echo "  DR kubeconfig:   $(_DR_KUBECONFIG)"
	@echo ""
	@echo "  This will:"
	@echo "    1. Pause ArgoCD auto-sync on both clusters"
	@echo "    2. Clean up ONTAP (SnapMirror, volumes, peers)"
	@echo "    3. Scrub AppVault S3 bucket"
	@echo "    4. Delete Crossplane-managed AWS resources (hub oc delete)"
	@echo "    5. AWS CLI fallback: remove any remaining FSx + VPC peering by tag/VPC pair"
	@echo "       (playbook fails if they still exist — needs aws configure / env creds)"
	@echo "=========================================="
	@echo ""
	@read -p "Type 'yes' to confirm: " confirm && [ "$$confirm" = "yes" ] || (echo "Aborted."; exit 1)
	ansible-playbook $(EXTRA_PLAYBOOK_OPTS) ansible/crossplane-destroy.yaml \
		-e @ansible/crossplane-vars.yml \
		$(_DR_EXTRA_VARS)

##@ Code quality (Biome — JSON formatter parity with GitHub super-linter v8)

.PHONY: deps-js lint-biome format-biome

deps-js: ## Install Node devDependencies (Biome); uses package-lock.json
	npm ci

lint-biome: deps-js ## Run Biome check (format + lint) on the repo
	npm run lint:biome

format-biome: deps-js ## Write Biome formatting (e.g. Grafana dashboard JSON)
	npm run format:biome
