---
global:
  pattern: netapp-dr-starter-kit
  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic

tridentProtect:
  appVault:
    enabled: true
    name: s3-appvault
    s3:
      bucketName: trident-protect-bucket
      region: us-west-1

  applications:
    - name: boutique
      namespaces:
        - name: boutique
    - name: wordpress
      namespaces:
        - name: wordpress

main:
  clusterGroupName: hub
  multiSourceConfig:
    enabled: true
    clusterGroupGitRepoUrl: https://github.com/day0hero/clustergroup-chart
    clusterGroupChartGitRevision: resource_actions
    #clusterGroupChartVersion: "0.9.*"
