apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: eso-mariadb-password
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    name: {{ .Values.secretStoreRef.name }}
    kind: {{ .Values.secretStoreRef.kind }}
  target:
    name: {{ .Values.mariadbSecret.name }}
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        mariadb-root-password: |-
          {{ "{{ .rootPassword | trim }}" }}
        mariadb-password: |-
          {{ "{{ .password | trim }}" }}
  data:
    - secretKey: rootPassword
      remoteRef:
        key: {{ .Values.mariadbSecret.vaultKey }}
        property: {{ .Values.mariadbSecret.rootProperty }}
    - secretKey: password
      remoteRef:
        key: {{ .Values.mariadbSecret.vaultKey }}
        property: {{ .Values.mariadbSecret.property }}
