FROM registry.access.redhat.com/ubi9/ubi-minimal:latest

ARG TERRAFORM_VERSION=1.12.1
ARG YQ_VERSION=v4.45.4
ARG OC_VERSION=4.18

RUN microdnf install -y --nodocs \
        python3 python3-pip git jq tar gzip unzip openssh-clients \
    && microdnf clean all

RUN pip3 install --no-cache-dir \
        ansible-core boto3 kubernetes

RUN curl -fsSL "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip" \
        -o /tmp/terraform.zip \
    && unzip /tmp/terraform.zip -d /usr/local/bin/ \
    && rm /tmp/terraform.zip \
    && chmod +x /usr/local/bin/terraform

RUN curl -fsSL "https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64" \
        -o /usr/local/bin/yq \
    && chmod +x /usr/local/bin/yq

RUN curl -fsSL "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable-${OC_VERSION}/openshift-client-linux.tar.gz" \
        | tar -xzf - -C /usr/local/bin oc kubectl

RUN curl -fsSL "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" \
        -o /tmp/awscli.zip \
    && unzip /tmp/awscli.zip -d /tmp \
    && /tmp/aws/install \
    && rm -rf /tmp/aws /tmp/awscli.zip

RUN useradd -m -u 1001 pipeline
USER 1001
WORKDIR /home/pipeline

ENTRYPOINT ["/bin/bash"]
