{{- if and .Values.crossplaneBootstrap.enabled (.Values.crossplane.providerConfig.credentials.fromVault | default false) .Values.crossplaneBootstrap.externalSecrets.primaryClusterKubeconfig }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ocp-primary-cluster-kubeconfig
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    {{- include "crossplane-aws-infra.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: ocp-primary-cluster-kubeconfig
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        kubeconfig: "{{`{{ .kubeconfig }}`}}"
  data:
    - secretKey: kubeconfig
      remoteRef:
        key: secret/data/global/ocp-primary-cluster-kubeconfig
        property: kubeconfig
{{- end }}
