{{- if .Values.fsxOntap.secretsManager.enabled }}
{{- $instances := include "crossplane-aws-infra.fsxInstances" . | fromJsonArray }}
{{- $providerConfigRef := .Values.global.providerConfigRef }}
{{- $pwdSecret := .Values.fsxOntap.passwordSecret }}

{{- range $inst := $instances }}
---
apiVersion: secretsmanager.aws.upbound.io/v1beta1
kind: Secret
metadata:
  name: {{ $inst.name }}-fsxadminpassword
  labels:
    {{- include "crossplane-aws-infra.labels" $ | nindent 4 }}
spec:
  forProvider:
    region: {{ $inst.region }}
    name: {{ $inst.name }}-FsxAdminPassword
    description: "FSx Admin Password for {{ $inst.name }}"
    recoveryWindowInDays: 0
    tags:
      Name: {{ $inst.name }}
      {{- range $k, $v := $inst.tags }}
      {{ $k }}: {{ $v | quote }}
      {{- end }}
  providerConfigRef:
    name: {{ $providerConfigRef }}

---
apiVersion: secretsmanager.aws.upbound.io/v1beta1
kind: SecretVersion
metadata:
  name: {{ $inst.name }}-fsxadminpassword-ver
spec:
  forProvider:
    region: {{ $inst.region }}
    secretIdRef:
      name: {{ $inst.name }}-fsxadminpassword
    secretStringSecretRef:
      name: {{ $pwdSecret.name }}
      namespace: {{ $pwdSecret.namespace }}
      key: {{ $pwdSecret.fsxAdminKey }}
  providerConfigRef:
    name: {{ $providerConfigRef }}

---
apiVersion: secretsmanager.aws.upbound.io/v1beta1
kind: Secret
metadata:
  name: {{ $inst.name }}-svmadminpassword
  labels:
    {{- include "crossplane-aws-infra.labels" $ | nindent 4 }}
spec:
  forProvider:
    region: {{ $inst.region }}
    name: {{ $inst.name }}-SVMAdminPassword
    description: "SVM Admin Password for {{ $inst.name }}"
    recoveryWindowInDays: 0
    tags:
      Name: {{ $inst.name }}
      {{- range $k, $v := $inst.tags }}
      {{ $k }}: {{ $v | quote }}
      {{- end }}
  providerConfigRef:
    name: {{ $providerConfigRef }}

---
apiVersion: secretsmanager.aws.upbound.io/v1beta1
kind: SecretVersion
metadata:
  name: {{ $inst.name }}-svmadminpassword-ver
spec:
  forProvider:
    region: {{ $inst.region }}
    secretIdRef:
      name: {{ $inst.name }}-svmadminpassword
    secretStringSecretRef:
      name: {{ $pwdSecret.name }}
      namespace: {{ $pwdSecret.namespace }}
      key: {{ $pwdSecret.svmAdminKey }}
  providerConfigRef:
    name: {{ $providerConfigRef }}
{{- end }}
{{- end }}
